<?xml version="1.0"?>
<robot name="lidar" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="lidar3d_sensor"
    params="prefix mode name configuration geometry xyz rpy parent_link mesh_visual ros_namespace ">

    <xacro:property name="link_name" 
      value="${prefix}${name}_link" />
    <xacro:property name="joint_name" 
      value="${prefix}${name}_joint" />
    <xacro:property name="controller_name" 
      value="${prefix}${name}_controller" />
    <xacro:property name="parent_link_name" 
      value="${prefix}${parent_link}" />

    <xacro:property name="mass" 
      value="${geometry['mass']}" />
    <xacro:property name="aabb_length" 
      value="${geometry['aabb']['length']}" />
    <xacro:property name="aabb_width" 
      value="${geometry['aabb']['width']}" />
    <xacro:property name="aabb_height" 
      value="${geometry['aabb']['height']}" />
    <xacro:property name="aabb_center" 
      value="${geometry['aabb']['center']}" />

    <xacro:if value="${mesh_visual == True and 'mesh' in geometry}">
      <xacro:property name="mesh_xyz" 
        value="${geometry['mesh']['xyz']}" />
      <xacro:property name="mesh_rpy" 
        value="${geometry['mesh']['rpy']}" />
      <xacro:property name="mesh_scale" 
        value="${geometry['mesh']['scale']}" />
      <xacro:property name="mesh_filename" 
        value="${geometry['mesh']['filename']}" />
    </xacro:if>

    <link name="${link_name}">
      <inertial>
        <mass value="${mass}" />
        <origin xyz="${aabb_center[0]} ${aabb_center[1]} ${aabb_center[2]}" />
        <inertia ixx="${0.0833333 * mass * (aabb_width*aabb_width + aabb_height*aabb_height)}"
          ixy="0.0" ixz="0.0"
          iyy="${0.0833333 * mass * (aabb_height*aabb_height + aabb_length*aabb_length)}" iyz="0.0"
          izz="${0.0833333 * mass * (aabb_length*aabb_length + aabb_width*aabb_width)}" />
      </inertial>
      <visual>
        <xacro:if value="${mesh_visual == True and 'mesh' in geometry}">
          <origin xyz="${mesh_xyz[0]} ${mesh_xyz[1]} ${mesh_xyz[2]}"
            rpy="${mesh_rpy[0]} ${mesh_rpy[1]} ${mesh_rpy[2]}" />
          <geometry>
            <mesh filename="${mesh_filename}"
              scale="${mesh_scale[0]} ${mesh_scale[1]} ${mesh_scale[2]}" />
          </geometry>
        </xacro:if>
        <xacro:if value="${mesh_visual == False or 'mesh' not in geometry}">
          <origin xyz="${aabb_center[0]} ${aabb_center[1]} ${aabb_center[2]}" rpy="0 0 0" />
          <geometry>
            <cylinder length="${aabb_height}" radius="${aabb_length / 2.0}" />
          </geometry>
        </xacro:if>
      </visual>
      <collision>
        <origin xyz="${aabb_center[0]} ${aabb_center[1]} ${aabb_center[2]}" rpy="0 0 0" />
        <geometry>
          <box size="${aabb_length} ${aabb_width} ${aabb_height}" />
        </geometry>
      </collision>

    </link>


    <xacro:if value="${'simulation' in  mode}">
      <xacro:include filename="$(find romea_lidar_description)/urdf/lidar3D.simulation.xacro" />
      <xacro:lidar3d_sensor_simulation
        prefix="${prefix}"
        mode="${mode}" 
        name="${name}"
        link_name="${link_name}" 
        configuration="${configuration}" 
        ros_namespace="${ros_namespace}"/>
    </xacro:if>


    <joint name="${joint_name}" type="fixed">
      <axis xyz="0 0 1" />
      <origin xyz="${xyz}" rpy="${rpy}" />
      <parent link="${parent_link_name}" />
      <child link="${link_name}" />
    </joint>

  </xacro:macro>

</robot>
