model:
  list: [os1_32, os1_64, os_128]
minimal_azimut_angle: -180.0
maximal_azimut_angle: 180.0
azimut_resolution:
  list: [0.703125, 0.3515625, 0.17578125]
azimut_angle_std: 0.0
samples:
  depend: azimut_resolution
  dict:
    0.703125: 512
    0.3515625: 1024
    0.17578125: 2048
minimal_elevation_angle: -22.5
maximal_elevation_angle: 22.5
elevation_resolution:
  depend: model
  dict:
    os1_32: 1.40625
    os1_64: 0.703125
    os1_128: 0.3515625
lasers:
  depend: model
  dict:
    os1_32: 32
    os1_64: 64
    os1_128: 128
elevation_angle_std: 0.0
minimal_range: 0.3
maximal_range: 55.0
range_std: 0.0
rate:
  list: [10, 20]
#
#
# type: 3D
# minimal_azimut_angle: -180.0
# maximal_azimut_angle: 180.0
# azimut_angle_increment: [0.703125, 0.3515625, 0.17578125]
# azimut_angle_std: 0.0
# samples: [512, 1024, 2048]
# minimal_elevation_angle: -22.5
# maximal_elevation_angle: 22.5
# elevation_angle_increment:
#   os1_32: 1.40625
#   os1_64: 0.703125
#   os1_128: 0.3515625
# lasers:
#   os1_32: 32
#   os1_64: 64
#   os1_128: 128
# elevation_angle_std: 0.0
# minimal_range: 0.3
# maximal_range: 55.0
# range_std: 0.0
# rate: [10, 20]

# type: 3D
# model:
#   list: [os1_32, os1_64, os_128]
# minimal_azimut_angle:
#   value: -180.0
#   unit: °
# maximal_azimut_angle:
#   value: 180.0
#   unit: °
# azimut_angle_increment:
#   list: [0.703125, 0.3515625, 0.17578125]
#   unit: °
# azimut_angle_std:
#   value: 0.0
#   unit: °
# samples:
#   depend: azimut_angle_increment
#   dict:
#     0.703125: 512
#     0.3515625: 1024
#     0.17578125: 2048
# minimal_elevation_angle:
#   value: -22.5
#   unit: °
# maximal_elevation_angle:
#   value: 22.5
#   unit: °
# elevation_angle_increment:
#   depend: model
#   dict:
#     os1_32: 1.40625
#     os1_64: 0.703125
#     os1_128: 0.3515625
#   unit: °
# lasers:
#   depend: model
#   dict:
#     os1_32: 32
#     os1_64: 64
#     os1_128: 128
# elevation_angle_std:
#   value: 0.0
#   unit: °
# minimal_range:
#   value: 0.3
#   unit: m
# maximal_range:
#   value: 55.0
#   unit: m
# range_std:
#   value: 0.0
#   unit: m
# rate:
#   list: [10, 20]
#   unit: Hz
