mass: 1.2
aabb:
    length: 0.085
    width: 0.085
    height: 0.0735
    center: [0.0, 0.0, 0.0]
mesh:
    xyz: [0.0, 0.0, 0.0]
    rpy: [1.5707, 0.0, 0.0]
    scale: [0.001, 0.001, 0.001]
    filename: "package://romea_lidar_description/meshes/ouster_os1.stl"
