minimal_azimut_angle: -135.0
maximal_azimut_angle: 135.0
azimut_angle_increment: [0.25, 0.125, 0.0625]
azimut_angle_std: 0.0
samples: [1081, 2161, 4321]
minimal_elevation_angle: -2.5
maximal_elevation_angle: 5
elevation_angle_increment: 2.5
elevation_angle_std: 0.0
lasers: 4
minimal_range: 0.5
maximal_range: 64.0
range_std: 0.0
rate: 50
