model:
  list:
    [
      lms100,
      lms101,
      lms102,
      lms111,
      lms121,
      lms122,
      lms123,
      lms131,
      lms132,
      lms133,
      lms141,
      lms142,
      lms143,
      lms151,
      lms153,
      lms161,
    ]
model_family:
  depend: model
  dict:
    lms100: lms10x
    lms101: lms10x
    lms102: lms10x
    lms111: lms11x
    lms121: lms12x
    lms122: lms12x
    lms123: lms12x
    lms131: lms13x
    lms132: lms13x
    lms133: lms13x
    lms141: lms14x
    lms142: lms14x
    lms143: lms14x
    lms151: lms15x
    lms153: lms15x
    lms161: lms16x
minimal_azimut_angle: -135.0
maximal_azimut_angle: 135.0
azimut_angle_std: 0.0
minimal_range: 0.5
maximal_range:
  depend: model_family
  dict:
    lms10x: 20.0
    lms11x: 20.0
    lms12x: 20.0
    lms13x: 20.0
    lms14x: 40.0
    lms15x: 50.0
range_std: 0.0
azimut_resolution:
  depend: rate
  dict:
    25: 0.25
    50: 0.5
samples:
  depend: rate
  dict:
    25: 1081
    50: 541
rate:
  list: [25, 50]
#
#
# type: 2D
# minimal_azimut_angle: -135.0
# maximal_azimut_angle: 135.0
# azimut_angle_std: 0.0
# minimal_range: 0.5
# maximal_range:
#   lms10x: 20.0
#   lms11x: 20.0
#   lms12x: 20.0
#   lms13x: 20.0
#   lms14x: 40.0
#   lms15x: 50.0
# range_std: 0.0
# azimut_angle_increment:
#   25hz: 0.25
#   50hz: 0.5
# samples:
#   25hz: 1081
#   50hz: 541
# rate: [25, 50]

# type: 2D
# model:
#   list:
#     [
#       lms100,
#       lms101,
#       lms102,
#       lms111,
#       lms121,
#       lms122,
#       lms123,
#       lms131,
#       lms132,
#       lms133,
#       lms141,
#       lms142,
#       lms143,
#       lms151,
#       lms153,
#       lms161,
#     ]
# model_family:
#   depend: model
#   dict:
#     lms100: lms10x
#     lms101: lms10x
#     lms102: lms10x
#     lms111: lms11x
#     lms121: lms12x
#     lms122: lms12x
#     lms123: lms12x
#     lms131: lms13x
#     lms132: lms13x
#     lms133: lms13x
#     lms141: lms14x
#     lms142: lms14x
#     lms143: lms14x
#     lms151: lms15x
#     lms153: lms15x
#     lms161: lms16x
# minimal_azimut_angle:
#   value: -135.0
#   unit: °
# maximal_azimut_angle:
#   value: 135.0
#   unit: °
# azimut_angle_std:
#   value: 0.0
#   unit: °
# azimut_angle_increment:
#   depend: rate
#   dict:
#     25: 0.25
#     50: 0.5
#   unit: °
# minimal_range:
#   value: 0.05
#   unit: m
# maximal_range:
#   depend: model_family
#   dict:
#     lms10x: 20.0
#     lms11x: 20.0
#     lms12x: 20.0
#     lms13x: 20.0
#     lms14x: 40.0
#     lms15x: 50.0
#   unit: m
# samples:
#   depend: rate
#   dict:
#     25: 1081
#     50: 541
# rate:
#   list: [25, 50]
#   unit: Hz
