minimal_azimut_angle: °
maximal_azimut_angle: °
azimut_resolution: °
azimut_angle_std: °
minimal_elevation_angle": °
maximal_elevation_angle": °
elevation_resolution": °
elevation_angle_std": °
minimal_range: m
maximal_range: m
range_std: m
rate: Hz
xyz: m
rpy: °
