driver:
  package: sick_scan_xd
  executable: sick_generic_caller
  plugin: none
  parameters:
    hostname:
      from: lidar_driver_configuration
    port:
      from: lidar_driver_configuration
    frame_id:
      from: lidar_configuration
      name: frame_id
    min_ang:
      from: lidar_configuration
      name: minimal_azimut_angle
      scale: pi/180.
    max_ang:
      from: lidar_configuration
      name: maximal_azimut_angle
      scale: pi/180.
    range_min:
      from: lidar_configuration
      name: minimal_range
    range_max:
      from: lidar_configuration
      name: maximal_range
    scanner_type: sick_tim_5xx
    # according sick_lms_1xx.launch from sick_scan_xd we need to specify these parameters
    range_filter_handling: 0
    intensity: True
    cloud_topic: cloud
    laserscan_topic: scan
    sw_pll_only_publish: True
    use_generation_timestamp: True
    ros_qos: -1
    tf_base_frame_id: foo
    tf_base_lidar_xyz_rpy: "0,0,0,0,0,0"
    tf_publish_rate: 0.0 # no tf published
    # use_binary_protocol: True
    # timelimit: 5
    # min_intensity: 0.0
    # tick_to_timestamp: 0
    # start_services: True
    # scandatacfg_timingflag: -1
    # add_transform_xyz_rpy: "0,0,0,0,0,0"
    # add_transform_check_dynamic_updates: False
    # message_monitoring_enabled: True
    # read_timeout_millisec_default: 5000
    # read_timeout_millisec_startup: 120000
    # read_timeout_millisec_kill_node: 150000
    # client_authorization_pw: F4724744
